#remote_theme : bitbrain/jekyll-dash
theme: jekyll-theme-cayman

# Setup
title:        Comunidad UBMI
tagline:      Tutoriales y recursos para los usuarios
baseurl:      "https://ubmi-ifc.github.io/Tutoriales-IFC/"
locale:       "es"

# About/contact
author:
  name:       UBMI-IFC
  url:        https://sites.google.com/ifc.unam.mx/ubmi-ifc/ 


