theme: jekyll-theme-minimal

# Setup
title: Comunidad UBMI
description: Tutoriales y recursos para los usuarios
markdown: GFM
google_analytics: <meta name="google-site-verification" content="R-114UTiVl1GE3elEcPI6BcmvBe7CHIhScSfi_2u7JM" />
logo: /assets/img/logo.png