theme: jekyll-theme-minimal

# Setup
title: Tutoriales UBMI IFC
description: Recursos para la comunidad
# markdown: GFM
google_analytics: <meta name="google-site-verification" content="R-114UTiVl1GE3elEcPI6BcmvBe7CHIhScSfi_2u7JM" />
logo: /assets/logo.png
show_downloads: false
plugins:
  - jekyll-sitemap
